### ISSUE TITLE
Wrong window selected when all aligned at the top

### ISSUE THREAD

**Issue by LnnrtS** [martinhjartmyr/gnome-shell-extension-focus-changer#1]
I have three windows that are aligned at the top and not overlapping each other. When I want to change focus from the most right one to the left, it skips the central one. Once I break the alignment it works.

I had a short look into the code and to me it seems the calculation of what window is the closest in a certain direction are a bit too simple. Or can you explain what the desired behaviour is?

**Comment by martinhjartmyr** [comment]
When changing focus in the X axel, the idea is to give window with the closest Y value priority. Even if it's not the closest in the X axel. (I find it works better if you have for example 4 windows open, one in each corner. Or just floating around)

If you have 3 windows tiled and they have the same Y value it should not skip the middle one. I can't reproduce it. How do you tile them? Are you using any extension for it? I could give it a try.

The algorithm calculating what window to focus can probably be improved. Feel free to open a pull request if you can improve it.

**Comment by LnnrtS** [comment]
> When changing focus in the X axel, the idea is to give window with the closest Y value priority. Even if it's not the closest in the X axel.

I see. But wouldn't it be better to first search for the closest in X direction and then use the Y coordinate as a second factor? That should also work for the 4 window setup you optimise for.

> If you have 3 windows tiled and they have the same Y value it should not skip the middle one. I can't reproduce it. How do you tile them? Are you using any extension for it? I could give it a try.

Currently I am tiling with the "tactile" gnome extension. But I see the skipping also if I align the windows by hand.

Unfortunately I don't have time to fix this myself at the moment.

**Comment by martinhjartmyr** [comment]
> I see. But wouldn't it be better to first search for the closest in X direction and then use the Y coordinate as a second factor? That should also work for the 4 window setup you optimise for.

As for now I'm just using the builtin shortcuts to tile "left side" and "right side" in gnome. If not tiled, I will have floating windows and I felt it was more natural to have it focus on the closest Y value when moving in X direction.

If I have time i will make a toggle in the preferences if it should prioritize the Y value or not. Thanks for the input!

**Comment by martinhjartmyr** [comment]
I was able to reproduce your issue with 3 windows in same Y value. It seems to be a bit random. I think it has to do with the order that the windows are looped if its a problem or not.

I will have a look at it.

**Comment by martinhjartmyr** [comment]
@LnnrtS update the extension, the issue should be solved.

**Comment by LnnrtS** [comment]
Left right works now. I am having problems moving down now though. No special alignment required, just position two windows with different Y and not overlapping. Is it the same for you?

**Comment by martinhjartmyr** [comment]
> Left right works now. I am having problems moving down now though. No special alignment required, just position two windows with different Y and not overlapping. Is it the same for you?

No, moving in all directions works. Tiled or floating. Could it gnome or something else hijacking the shortcut?

**Comment by LnnrtS** [comment]
You were right, the shortcut was already defined in gnome. Now everything works. Thanks for fixing it.

For the record: I was using `Ctrl` + `Alt` + `Up`/`Down` but that was already mapped to switching to a workspace below or above. These shortcuts are not shown in the gnome settings shortcut dialog, at least on my machine. I was still able to set them via dconf in `org.gnome.desktop.wm.keybindings`. I guess the reason is that I have workspaces aligned horizontally and there is never going to be a workspace below or above and so the shortcut isn't displayed.

**Comment by martinhjartmyr** [comment]
No problems! Thanks for raising the issue to help improve the extension.
