### ISSUE TITLE
Do you mind if I maintain this extension for GNOME 45?

### ISSUE THREAD

**Issue by pesader** [martinhjartmyr/gnome-shell-extension-focus-changer#13]
As you may know, every single shell extension was broken on GNOME 45, as it moved away from its own import system and into standard ESM modules. Since this extension is ingrained in my muscle-memory far past the point of no return, I decided to port it to the latest version of GNOME.

I also got a little too enthusiastic and ended up porting the preferences screen to libadwaita, added support for translations, and translated it to my mother language (Brazilian Portuguese).

![Screenshot from 2023-09-30 22-57-32](https://github.com/martinhjartmyr/gnome-shell-extension-focus-changer/assets/65264536/01173c8a-fe6e-4b4c-82d0-4153fa6aaac9)

I was going to submit a few pull requests with these changes but, since I saw that the last commit was also my own port to GNOME 44, I wanted to ask you if you would like to me to maintain the extension from here on out. It would be an honor give continuation to the amazing work you've done on Focus Changer! 😁 🚀

**Comment by martinhjartmyr** [comment]
Awesome work @pesader, I've sent you an email.

**Comment by pesader** [comment]
Thanks! The email didn't get to my inbox though 🤔
Could you send another one, please?
