### ISSUE TITLE
Cannot Assign Super + I

### ISSUE THREAD

**Issue by eeriemyxi** [martinhjartmyr/gnome-shell-extension-focus-changer#17]
When I try to assign Super + I, it cannot detect me pressing it.

https://github.com/martinhjartmyr/gnome-shell-extension-focus-changer/assets/86738916/fd91b52d-331b-4b14-adb3-6542acb3f659

But I can assign it in the system settings.

**Comment by martinhjartmyr** [comment]
Strange, I'm not sure how we can debug that.

You can try to create the shortcut manually using dconf:
/org/gnome/shell/extensions/focus-changer/focus-right ['<Super>l']

**Comment by eeriemyxi** [comment]
I shortly after that gave up on GNOME DE for some other reasons. Because I don't intend to install it, I feel this issue is better closed until another person encounters it. Thanks for the support.
