### ISSUE TITLE
Ignore minimized windows

### ISSUE THREAD

**Issue by LnnrtS** [martinhjartmyr/gnome-shell-extension-focus-changer#2]
When changing focus, minimized windows should not be taken into account for being the next best window in any direction.

Currently this is not the case. Minimized windows are handled with their last non-minimized position and once they receive focus they are restored at that position.

**Comment by martinhjartmyr** [comment]
Solved in e5d98b9d6430ce1974125799bc8ffcc9466b2105 and e6389efb2d3ac70752386170330788388a711471
