### ISSUE TITLE
Support for Gnome 43

### ISSUE THREAD

**Issue by cnrrobertson** [martinhjartmyr/gnome-shell-extension-focus-changer#9]
Thank you for this amazing extension. I'd love to take it with me into Gnome 43. Any plans for this?

**Comment by martinhjartmyr** [comment]
Yes! I have not yet had time to update gnome and test it. I will do it asap.

**Comment by martinhjartmyr** [comment]
Ran into some problems with gdm and mutter [https://bugs.archlinux.org/task/76368](https://bugs.archlinux.org/task/76368)

Had to spend the evening rolling back the upgrade instead of testing it. I will give a go again in a day or two.

**Comment by martinhjartmyr** [comment]
Works fine in Gnome 43. I have submitted an update.

**Comment by cnrrobertson** [comment]
Thank you!
